# Generated by Django 5.0 on 2026-09-14 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Check this box if the review is inappropriate. It will be hidden from the movie page.'),
        ),
        migrations.CreateModel(
            name='ReviewFlag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flag', models.CharField(db_index=True, default='removal suggestion', max_length=30)),
                ('flag_date', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='movies.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'review', 'flag')},
            },
        ),
    ]
